In [132]:
import pandas as pd
import numpy as np
import seaborn as sns
from datetime import datetime
from haversine import haversine

ModuleNotFoundError: No module named 'haversine'

In [ ]:
cc_df = pd.read_csv('fraud.csv')

In [ ]:
pd.set_option('display.max_columns', 50)

In [ ]:
cc_df.head()

,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,city,state,zip,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,Orient,WA,99160,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
1,2019-01-01 00:12:34,4956828990005111019,"fraud_Schultz, Simonis and Little",grocery_pos,44.71,Kenneth,Robinson,M,269 Sanchez Rapids,Elizabeth,NJ,7208,40.6747,-74.2239,124967,Operational researcher,1980-12-21,09eff9c806365e2a6be12c1bbab3d70e,1325376754,40.079588,-74.848087,0
2,2019-01-01 00:17:16,180048185037117,fraud_Kling-Grant,grocery_net,46.28,Mary,Wall,F,2481 Mills Lock,Plainfield,NJ,7060,40.6152,-74.4150,71485,Leisure centre manager,1974-07-19,19e23c6a300c774354417befe4f31f8c,1325377036,40.021888,-74.228188,0
3,2019-01-01 00:20:15,374930071163758,fraud_Deckow-O'Conner,grocery_pos,64.09,Daniel,Escobar,M,61390 Hayes Port,Romulus,MI,48174,42.2203,-83.3583,31515,Police officer,1971-11-05,6f363661ba6b55889e488dd178f2a0af,1325377215,42.360426,-83.552316,0
4,2019-01-01 00:23:41,2712209726293386,fraud_Balistreri-Nader,misc_pos,25.58,Jenna,Brooks,F,50872 Alex Plain Suite 088,Baton Rouge,LA,70808,30.4066,-91.1468,378909,"Designer, furniture",1977-02-22,1654da2abfb9e79a5f99167fc9779558,1325377421,29.737426,-90.853194,0

In [ ]:
cc_df[cc_df['is_fraud'] == 1]

,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,city,state,zip,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
4794,2019-01-12 00:59:01,581686439828,"fraud_Zieme, Bode and Dooley",gas_transport,11.73,Larry,House,M,911 Sabrina Trafficway,Cochranton,PA,16314,41.5205,-80.0573,5507,Retail merchandiser,1973-07-28,77c44b4cff9a624f54d389887605dbb2,1326329941,41.947427,-79.796264,1
4816,2019-01-12 03:48:07,581686439828,fraud_Koepp-Witting,grocery_pos,328.68,Larry,House,M,911 Sabrina Trafficway,Cochranton,PA,16314,41.5205,-80.0573,5507,Retail merchandiser,1973-07-28,90e7917ee506a5b1ea068bdf2fac064b,1326340087,42.148618,-79.398595,1
4979,2019-01-12 15:46:10,581686439828,fraud_Abernathy and Sons,food_dining,120.58,Larry,House,M,911 Sabrina Trafficway,Cochranton,PA,16314,41.5205,-80.0573,5507,Retail merchandiser,1973-07-28,aaac448ccb3f869994c4f1cad95dba18,1326383170,42.470024,-80.126576,1
5073,2019-01-12 19:53:59,581686439828,fraud_Boyer-Reichert,shopping_net,1081.35,Larry,House,M,911 Sabrina Trafficway,Cochranton,PA,16314,41.5205,-80.0573,5507,Retail merchandiser,1973-07-28,8545f40c91a37f8015749b0f962cff20,1326398039,42.455406,-79.521640,1
5124,2019-01-12 22:44:05,581686439828,fraud_Fisher-Schowalter,shopping_net,776.70,Larry,House,M,911 Sabrina Trafficway,Cochranton,PA,16314,41.5205,-80.0573,5507,Retail merchandiser,1973-07-28,3b6d88a3c7349cb3ee408bce6e4ffac2,1326408245,40.680209,-79.099101,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
477832,2020-12-21 02:21:41,4716561796955522,fraud_Murray-Smitham,grocery_pos,358.24,Lauren,Anderson,F,11014 Chad Lake Apt. 573,Heart Butte,MT,59448,48.2777,-112.8456,743,Water engineer,1972-05-04,8a5d80eb4f573480db90899dd8b1c34a,1387592501,47.526202,-113.643313,1
477847,2020-12-21 02:36:03,4716561796955522,fraud_Schmidt and Sons,shopping_net,859.12,Lauren,Anderson,F,11014 Chad Lake Apt. 573,Heart Butte,MT,59448,48.2777,-112.8456,743,Water engineer,1972-05-04,fe8464ee336fe08b2adacdd0867b1343,1387593363,48.272348,-112.328075,1
479296,2020-12-21 22:38:38,4716561796955522,fraud_Quitzon-Goyette,home,209.84,Lauren,Anderson,F,11014 Chad Lake Apt. 573,Heart Butte,MT,59448,48.2777,-112.8456,743,Water engineer,1972-05-04,7cde9b7604a025e251756a4bc9615888,1387665518,49.173669,-112.698767,1
479305,2020-12-21 22:42:11,4716561796955522,fraud_Schulist Ltd,food_dining,123.58,Lauren,Anderson,F,11014 Chad Lake Apt. 573,Heart Butte,MT,59448,48.2777,-112.8456,743,Water engineer,1972-05-04,daabc7ccf6ccf2c85c1f6186ca11193a,1387665731,48.913048,-113.214921,1
479341,2020-12-21 22:59:22,4716561796955522,fraud_Botsford and Sons,home,219.11,Lauren,Anderson,F,11014 Chad Lake Apt. 573,Heart Butte,MT,59448,48.2777,-112.8456,743,Water engineer,1972-05-04,4de4d5177b9b5c2054a638583ba63a3d,1387666762,47.911219,-113.691603,1

In [ ]:
cc_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 491134 entries, 0 to 491133
Data columns (total 22 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   trans_date_trans_time  491134 non-null  object
 1   cc_num                 491134 non-null  int64
 2   merchant               491134 non-null  object
 3   category               491134 non-null  object
 4   amt                    491134 non-null  float64
 5   first                  491134 non-null  object
 6   last                   491134 non-null  object
 7   gender                 491134 non-null  object
 8   street                 491134 non-null  object
 9   city                   491134 non-null  object
 10  state                  491134 non-null  object
 11  zip                    491134 non-null  int64
 12  lat                    491134 non-null  float64
 13  long                   491134 non-null  float64
 14  city_pop               491134 non-null  int64
 15  job                    491134 non-null  object
 16  dob                    491134 non-null  object
 17  trans_num              491134 non-null  object
 18  unix_time              491134 non-null  int64
 19  merch_lat              491134 non-null  float64
 20  merch_long             491134 non-null  float64
 21  is_fraud               491134 non-null  int64
dtypes: float64(5), int64(5), object(12)
memory usage: 82.4+ MB

In [ ]:
cc_df.describe()

,cc_num,amt,zip,lat,long,city_pop,unix_time,merch_lat,merch_long,is_fraud
count,4.911340e+05,491134.000000,491134.000000,491134.000000,491134.000000,4.911340e+05,4.911340e+05,491134.000000,491134.000000,491134.000000
mean,3.706013e+17,69.050120,50770.532384,37.931230,-90.495619,1.213922e+05,1.358730e+09,37.930272,-90.495411,0.002533
std,1.260229e+18,160.322867,26854.947965,5.341193,12.990732,3.725751e+05,1.819402e+07,5.372986,13.004100,0.050264
min,5.038744e+11,1.000000,1843.000000,24.655700,-122.345600,4.600000e+01,1.325376e+09,23.655789,-123.345106,0.000000
25%,2.131124e+14,8.960000,28405.000000,33.746700,-97.235100,1.228000e+03,1.343087e+09,33.781388,-96.984814,0.000000
50%,3.531130e+15,42.170000,49628.000000,38.507200,-87.591700,5.760000e+03,1.357257e+09,38.545124,-87.573441,0.000000
75%,4.653879e+15,80.330000,75048.000000,41.520500,-80.731000,5.083500e+04,1.374626e+09,41.624294,-80.685567,0.000000
max,4.956829e+18,25086.940000,99323.000000,48.887800,-69.965600,2.906700e+06,1.388534e+09,49.887523,-68.965624,1.000000

In [ ]:
cc_df.columns

Index(['trans_date_trans_time', 'cc_num', 'merchant', 'category', 'amt',
       'first', 'last', 'gender', 'street', 'city', 'state', 'zip', 'lat',
       'long', 'city_pop', 'job', 'dob', 'trans_num', 'unix_time', 'merch_lat',
       'merch_long', 'is_fraud'],
      dtype='object')

trans_date_trans_time(Transaction Date & Transaction Time): 거래 발생 일시(날짜+시간)

trans_num(Transaction Number): 거래 고유번호(문자열 ID)

unix_time (Unix Timestamp / Seconds since Epoch): 거래시간을 초(Seconds)로 바꾼 값(1970-01-01 기준)


카드/고객(개인 식별 가능 정보 포함)

cc_num(Credit Card Number): 카드번호(개인 식별 가능 / 고카디널리티)

dob(Date of Birth): 생년월일


거래처/업종

merchant(Merchant Name): 가맹점 이름(고카디널리티)

category(Merchant Category): 가맹점 업종 카테고리(예: gas_transport 등)

amt(Amount): 결제 금액

주소/지역(고객 위치)

street(Street Address): 도로명/상세주소

zip(ZIP Code / Postal Code): 우편번호

lat(Latitude): 고객 주소 위도

long(Longitude): 고객 주소 경도

city_pop(City Population): 도시 인구(규모 변수)

가맹점 위치(거래 발생 위치)

merch_lat(Merchant Latitude): 가맹점 위도

merch_long(Merchant Longitude): 가맹점 경도


타깃

is_fraud(Is Fraud): 사기 여부(1=사기, 0=정상)

### **불필요한 컬럼 삭제**

In [ ]:
drop_cols = ["trans_num", "cc_num", "first", "last", "trans_dt", "street", "city", "zip", "job", "merchant", "unix_time"]
cc_df = cc_df.drop(columns=drop_cols, errors="ignore")
cc_df.shape

(491134, 12)

### **컬럼 이름 통일**

In [ ]:
cc_df = cc_df.rename(columns={
    "lat": "cust_lat",
    "long": "cust_lon",
    "merch_lat": "merch_lat",
    "merch_long": "merch_lon",
    "trans_date_trans_time": "trans_dt"
})
cc_df.head()

,trans_dt,category,amt,gender,state,cust_lat,cust_lon,city_pop,dob,merch_lat,merch_lon,is_fraud
0,2019-01-01 00:00:44,grocery_pos,107.23,F,WA,48.8878,-118.2105,149,1978-06-21,49.159047,-118.186462,0
1,2019-01-01 00:12:34,grocery_pos,44.71,M,NJ,40.6747,-74.2239,124967,1980-12-21,40.079588,-74.848087,0
2,2019-01-01 00:17:16,grocery_net,46.28,F,NJ,40.6152,-74.4150,71485,1974-07-19,40.021888,-74.228188,0
3,2019-01-01 00:20:15,grocery_pos,64.09,M,MI,42.2203,-83.3583,31515,1971-11-05,42.360426,-83.552316,0
4,2019-01-01 00:23:41,misc_pos,25.58,F,LA,30.4066,-91.1468,378909,1977-02-22,29.737426,-90.853194,0

### **고객 생일을 나이로 계산**

In [ ]:
cc_df.head()

,trans_dt,category,amt,gender,state,cust_lat,cust_lon,city_pop,dob,merch_lat,merch_lon,is_fraud
0,2019-01-01 00:00:44,grocery_pos,107.23,F,WA,48.8878,-118.2105,149,1978-06-21,49.159047,-118.186462,0
1,2019-01-01 00:12:34,grocery_pos,44.71,M,NJ,40.6747,-74.2239,124967,1980-12-21,40.079588,-74.848087,0
2,2019-01-01 00:17:16,grocery_net,46.28,F,NJ,40.6152,-74.4150,71485,1974-07-19,40.021888,-74.228188,0
3,2019-01-01 00:20:15,grocery_pos,64.09,M,MI,42.2203,-83.3583,31515,1971-11-05,42.360426,-83.552316,0
4,2019-01-01 00:23:41,misc_pos,25.58,F,LA,30.4066,-91.1468,378909,1977-02-22,29.737426,-90.853194,0

In [ ]:
cc_df["trans_dt"] = pd.to_datetime(cc_df["trans_dt"], errors="coerce")

In [ ]:
cc_df['dob_dt'] = pd.to_datetime(cc_df['dob'], errors= 'coerce')

In [ ]:
cc_df["age"] = (cc_df["trans_dt"] - cc_df["dob_dt"]).dt.days // 365

In [ ]:
cc_df.head()

,trans_dt,category,amt,gender,state,cust_lat,cust_lon,city_pop,dob,merch_lat,merch_lon,is_fraud,dob_dt,age
0,2019-01-01 00:00:44,grocery_pos,107.23,F,WA,48.8878,-118.2105,149,1978-06-21,49.159047,-118.186462,0,1978-06-21,40
1,2019-01-01 00:12:34,grocery_pos,44.71,M,NJ,40.6747,-74.2239,124967,1980-12-21,40.079588,-74.848087,0,1980-12-21,38
2,2019-01-01 00:17:16,grocery_net,46.28,F,NJ,40.6152,-74.4150,71485,1974-07-19,40.021888,-74.228188,0,1974-07-19,44
3,2019-01-01 00:20:15,grocery_pos,64.09,M,MI,42.2203,-83.3583,31515,1971-11-05,42.360426,-83.552316,0,1971-11-05,47
4,2019-01-01 00:23:41,misc_pos,25.58,F,LA,30.4066,-91.1468,378909,1977-02-22,29.737426,-90.853194,0,1977-02-22,41

### **확인용**

In [ ]:
cc_df[cc_df["amt"] < 0]

Empty DataFrame
Columns: [trans_dt, category, amt, gender, state, cust_lat, cust_lon, city_pop, dob, merch_lat, merch_lon, is_fraud, dob_dt, age]
Index: []

In [ ]:
cc_df[cc_df["age"] < 20]

,trans_dt,category,amt,gender,state,cust_lat,cust_lon,city_pop,dob,merch_lat,merch_lon,is_fraud,dob_dt,age
14,2019-01-01 00:55:05,gas_transport,57.23,M,AR,35.5762,-91.4539,111,2000-06-13,36.144895,-92.188172,0,2000-06-13,18
27,2019-01-01 01:47:09,grocery_net,53.87,F,KY,37.0581,-86.1938,6841,1999-06-06,36.784818,-86.369122,0,1999-06-06,19
29,2019-01-01 01:50:26,grocery_net,55.81,M,IL,39.5723,-90.2379,1512,2003-05-07,39.575819,-90.149623,0,2003-05-07,15
44,2019-01-01 03:04:28,grocery_net,25.89,F,IL,41.0646,-87.5917,2135,2004-05-08,40.888445,-87.409615,0,2004-05-08,14
45,2019-01-01 03:10:00,gas_transport,77.59,F,IL,41.0646,-87.5917,2135,2004-05-08,41.818260,-88.129609,0,2004-05-08,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
490975,2020-12-31 21:15:45,travel,7.05,F,KS,39.1329,-95.7023,163415,2004-12-30,39.998111,-95.452864,0,2004-12-30,16
490993,2020-12-31 21:40:08,misc_net,2.91,F,KS,39.1329,-95.7023,163415,2004-12-30,38.519571,-96.429821,0,2004-12-30,16
491033,2020-12-31 22:13:47,entertainment,4.88,F,KS,39.1329,-95.7023,163415,2004-12-30,39.906783,-94.914010,0,2004-12-30,16
491075,2020-12-31 22:54:39,misc_pos,111.34,F,IL,41.0646,-87.5917,2135,2004-05-08,41.534827,-87.779693,0,2004-05-08,16
491118,2020-12-31 23:36:15,shopping_net,25.07,M,IL,39.5723,-90.2379,1512,2003-05-07,39.708279,-90.792116,0,2003-05-07,17

In [ ]:
cc_df[cc_df["age"] > 100]

Empty DataFrame
Columns: [trans_dt, category, amt, gender, state, cust_lat, cust_lon, city_pop, dob, merch_lat, merch_lon, is_fraud, dob_dt, age]
Index: []

In [ ]:
cc_df["age"].describe()

count    491134.000000
mean         34.671475
std           9.297933
min          14.000000
25%          27.000000
50%          35.000000
75%          43.000000
max          50.000000
Name: age, dtype: float64

### **불필요한 컬럼 삭제**

In [ ]:
cc_df.columns

Index(['trans_dt', 'category', 'amt', 'gender', 'state', 'cust_lat',
       'cust_lon', 'city_pop', 'dob', 'merch_lat', 'merch_lon', 'is_fraud',
       'dob_dt', 'age'],
      dtype='object')

In [ ]:
drop_cols = ['dob', 'dob_dt']
cc_df = cc_df.drop(columns=drop_cols, errors="ignore")
cc_df.head()

,trans_dt,category,amt,gender,state,city_pop,merch_lat,merch_lon,is_fraud,age,log_amt
0,2019-01-01 00:00:44,grocery_pos,107.23,F,WA,149,49.159047,-118.186462,0,40,4.684259
1,2019-01-01 00:12:34,grocery_pos,44.71,M,NJ,124967,40.079588,-74.848087,0,38,3.822317
2,2019-01-01 00:17:16,grocery_net,46.28,F,NJ,71485,40.021888,-74.228188,0,44,3.856087
3,2019-01-01 00:20:15,grocery_pos,64.09,M,MI,31515,42.360426,-83.552316,0,47,4.175771
4,2019-01-01 00:23:41,misc_pos,25.58,F,LA,378909,29.737426,-90.853194,0,41,3.280159

### **거래 시간대**

In [ ]:
hour, weekday/weekend
cc_df['trans_dt'] = pd.to_datetime(cc_df['trans_dt'])
cc_df['hour'] = cc_df['trans_dt'].dt.hour
cc_df['weekday'] = cc_df['trans_dt'].dt.weekday   # 0=월, 6=일
cc_df['is_weekend'] = cc_df['weekday'].isin([5,6]).astype(int)